### ISSUE TITLE
Page Redirected Too Many Times

### ISSUE THREAD

**Issue by j2is** [nilsenpaul/craft-sequentialedit#2]
Unfortunately I can't get the plugin to work, selecting just two posts it says "This page redirected you too many times."

**Comment by j2is** [comment]
I made a repo to reproduce the issue
https://github.com/j2is/sequential-edit-issue

**Comment by nilsenpaul** [comment]
Fixed by https://github.com/nilsenpaul/craft-sequentialedit/commit/1b91b4254e6b8419042b04fb5f7447e4f9056a38. Thanks for your patience and assistance!

**Comment by mannachurch** [comment]
I updated to the latest version and I have no problems with the install but now I get the error "This page redirected you too many times." I thought it could be because the number of entries I was trying but even when I just try with 10 entries, I still get the same error.

**Comment by nilsenpaul** [comment]
@mannachurch What version are you on, now? The latest version is v1.0.5, but I guess that didn't get through to the plugin store, yet. If you are not on version 1.0.5, could you try to adjust your `composer.json` to use 1.0.5 and run `composer update`? Please let me know if that solves the problem!
